### ISSUE TITLE
Account creation

### ISSUE THREAD

**Issue by jonnybroughton** [jonnybroughton/project-portfolio-4#2]
As a **Site User** I can **create an account** so that **I can interact with the site to a greater extent**

### Acceptance criteria

- Acceptance criteria 1: The user can create an account using a username and password
- Acceptance criteria 2: The user, when logged in can interact with the site beyond the functionality of a non-logged-in user, such as leaving a comment or upvoting/downvoting a post to incentivise account creation
- Acceptance criteria 3: The user can also remain logged out and view the site in a read-only format

**Comment by emadellaloggia** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6

you may need to install the c compiler
